name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
      - uses: taiki-e/install-action@cargo-hack
      - name: Test features
        run: cargo hack check --all --each-feature --clean-per-run --no-dev-deps
      - name: Install
        run: cargo install cargo-edit
      - name: Check bump
        run: |
          if [[ "${{ github.event.inputs.release_version }}" != "patch" ]]; then cargo set-version --bump ${{ github.event.inputs.release_version }}; fi
      - name: Publish
        shell: bash
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --dry-run
      - name: Prepare next version
        run: cargo set-version --bump patch
      - name: Check
        run: cat Cargo.toml

